name: uppuveli
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  # iOS style icons (recommended)
  cupertino_icons: ^1.0.8


  flutter_stripe: ^11.0.0
  http: ^1.2.0


  # Firebase core
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  flutter_facebook_auth: ^7.0.0


  # Social login
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3


  share_plus: ^10.0.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
